#!/bin/bash
echo "BlockRock Project Summary"
echo "------------------------"
echo "Date: $(date)"
echo "Git Branch: $(git rev-parse --abbrev-ref HEAD)"
echo "Git Commit: $(git rev-parse --short HEAD)"
echo "Cargo Version: $(cargo --version)"
echo "Rust Version: $(rustc --version)"
echo "Node Status:"
curl -s http://localhost:8000/health || echo "Node not running"
echo "Tron Balance:"
curl -s http://localhost:8000/tron_balance || echo "Failed to get tron_balance"
echo "Modules:"
curl -s http://localhost:8000/modules || echo "Failed to get modules"
echo "------------------------"
