[package]
name = "blockrock-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "blockrock_core"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "serde"] }
rand = "0.8"
hex = "0.4"
