[package]
name = "zion-core"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = "0.53.0"
prometheus = "0.13"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
tonic = "0.8"
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "serde"] }
rand = "0.8"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
